### ISSUE TITLE
Make the docusafe 2 deploy to travis and the module deploy to maven central

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/docusafe2#16]

**Comment by electronicpeter** [comment]
Done by maksym. Still missing the key for maven central.

**Comment by electronicpeter** [comment]
ask joe for key

**Comment by electronicpeter** [comment]
To remember what was done and what has to be done in s the future see https://github.com/adorsys/docusafe2/blob/develop/docs/general/deployment_maven_central.md
